# Generated by Django 3.1.3 on 2020-11-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='is_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
