# Generated by Django 3.1.3 on 2020-11-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_api_is_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='name',
            new_name='customer_xid',
        ),
    ]
