# Generated by Django 3.1.3 on 2020-11-05 06:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201105_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='api',
            name='enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
