# Generated by Django 3.1.3 on 2020-11-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201105_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='status',
            field=models.CharField(default='disabled', max_length=50),
        ),
    ]
