# Generated by Django 3.1.3 on 2020-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_api_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='deposited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
