# Generated by Django 3.1.3 on 2020-11-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_api_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='reference_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
