# Generated by Django 3.1.3 on 2020-11-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201105_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='history_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
